import streamlit as st
from PIL import Image
import io

# GPT-4o API endpoint (placeholder, plug your own once you get the key)
GPT_4O_API_ENDPOINT = "https://api.openai.com/v1/chat/completions"
HEADERS = {
    "Authorization": "Bearer YOUR_OPENAI_API_KEY",
    "Content-Type": "application/json"
}

# Get ticket_id from URL or previous step
ticket_id = st.query_params.get("ticket_id", None)

st.set_page_config(page_title="Upload Accident Photos", page_icon="📷")

if not ticket_id:
    st.warning("once the ticket is formed,we will get ahead with image uploads.")
    st.stop()

st.title(" Upload Accident Photos for FNOL Ticket")
st.markdown(f"**Ticket ID:** `{ticket_id}`")

uploaded_images = st.file_uploader(
    "Upload photos (JPEG/PNG) for summarization", type=["jpg", "jpeg", "png"], accept_multiple_files=True
)
if uploaded_images:
    st.success(f"{len(uploaded_images)} image(s) uploaded.")
    for img in uploaded_images:
        st.image(img, caption=img.name, use_column_width=True)

    if st.button("📄 Summarize & Confirm FNOL"):
        with st.spinner("Generating summary with GPT-4o..."):
            base64_images = [
                {
                    "image": img.read(),
                    "name": img.name
                }
                for img in uploaded_images
            ]

            # 👇 This part should be implemented to call GPT-4o vision once key is available
            # We'll mock this step for now.
            mock_summary = "The images show a broken rear bumper, minor dent on the left door, and some paint scratches. No visible injuries."

            st.success("✅ Summary generated by GPT-4o:")
            st.info(mock_summary)

            st.markdown("### ✅ Your FNOL ticket is now fully documented.")
else:
    st.info("Please upload at least one image to proceed.")
